djangowhp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('warehouses.urls')),
]

user/urls.py
# user.urls.py

from django.urls import path, include
from warehouses.views import RegisterView
from .views import (
    LoginView,
    SignUpView,
    UpdateUserView,
    ContactView,
    custom_logout,
    LoginRequiredView,
    ConnectEmployeeView,
    reply_to_contact
)

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login_to_cli_account/", ConnectEmployeeView.as_view(), name="connect_employee"),
    path("account/<int:pk>", UpdateUserView.as_view(), name="account"),
    path('auth/', include('django.contrib.auth.urls')),
    path('logout/', custom_logout, name="logout"),
    path("login/", LoginView.as_view(), name="login"),
    path("login_required/", LoginRequiredView.as_view(), name="login_required"),
    path('reply/<int:contact_id>/', reply_to_contact, name='reply_to_contact'),

]

warehouses/urls.py
from django.urls import path
from .views import (
    NotFound,
    Index,
    Warehouse,
    About,
    Products,
    ProductDetailView,
    List_Filtered,
    List_Items_Filtered,
    Search_Items,
    Search_Items_Result,
    WorkingHoursView,
    OrderView,
    Thanks
)

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("about/", About.as_view(), name="about"),
    path("not_found/", NotFound.as_view(), name="not_found"),
    path("thanks/<str:action>", Thanks.as_view(), name="thanks"),
    path("<str:location>/", Warehouse.as_view(), name="warehouse"),
    path("<str:location>/products/", Products.as_view(), name="products"), # list items per warehouse
    path("<str:location>/order/<str:state>/<str:category>/", OrderView.as_view(), name="order"),
    path("stock/employees/", WorkingHoursView.as_view(), name="list_workinhours"),
    path("product/<int:pk>", ProductDetailView.as_view(), name="product_detail"), # edit items per warehouse
    path("<str:location>/search/", Search_Items.as_view(), name="search"), # search items per warehouse
    path("<str:location>/search/<str:search_term>", Search_Items_Result.as_view(), name="search_result"), # search items per warehouse
    path("<str:location>/<str:filter>/<str:filter_string>/", List_Items_Filtered.as_view(), name="filtered_items"), #items browser
    path("<str:location>/<str:filter>/", List_Filtered.as_view(), name="filtered"), #list categories/states per warehouse
]

warehouses/models.py
from django.db import models
from django.contrib.auth.models import User
from cli.toys import glued_string
from django.core.exceptions import ValidationError
import json
from datetime import datetime
from functools import partial

# Create your models here.

class Employee(models.Model):
    '''Model for employees'''
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    head_of = models.ManyToManyField('self', symmetrical=False, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class Warehouse(models.Model):
    '''Model for the warehouses'''
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

def validate_dimensions(value):
    # If value is None, it's valid
    if value is None:
        return
    
    # Check if all keys other than 'height', 'width', and 'depth' are absent
    allowed_keys = {'height', 'width', 'depth'}
    for key in value.keys():
        if key not in allowed_keys:
            raise ValidationError(f"Invalid key '{key}' found. Only 'height', 'width', and 'depth' are allowed.")
        
    json_string = json.dumps(value)
    return json_string

def _get_state_choices():
    return [(value, value) for value in Item.objects.values_list("state", flat=True).distinct()]


def _get_category_choices():
    return [(value, value) for value in Item.objects.values_list("category", flat=True).distinct()]


class Item(models.Model):
    '''Model For warehouse Items'''
    state = models.CharField(max_length=100)#, choices=partial(_get_state_choices))
    category = models.CharField(max_length=100)#, choices=partial(_get_category_choices))
    warehouse = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    date_of_stock = models.DateTimeField()
    name = models.CharField(max_length=100, null=True)
    dimensions = models.JSONField(null=True, blank=True, validators=[validate_dimensions])
    shipped = models.BooleanField(default=False)

    def get_default_item_name(self, state, category):
        if category[-1] != "s":
            return f"{glued_string(state)} {category.lower()}"
        else:
            return f"{state} {category.lower()}"

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.get_default_item_name(self.state, self.category)
        super().save(*args, **kwargs)


class ItemEdit(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    edited_at = models.DateTimeField(auto_now_add=True)



class ItemOrder(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    item =models.ManyToManyField(Item, related_name='ordered_items')
    amount = models.IntegerField()
    ordered_at = models.DateTimeField(auto_now_add=True)


class Communication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    message = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)


class Contact(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    communications = models.ManyToManyField(Communication, related_name='contacts')


class EmployeeWorkingHours(models.Model):
    WEEKDAY_CHOICES = (
        (0, 'Monday'),
        (1, 'Tuesday'),
        (2, 'Wednesday'),
        (3, 'Thursday'),
        (4, 'Friday'),
        (5, 'Saturday'),
    )

    week_day = models.IntegerField(choices=WEEKDAY_CHOICES)
    start_time = models.TimeField()
    end_time = models.TimeField()
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)


def populate_emp_working_hours():
    from random import randint

    for emp in Employee.objects.all():
        work_days = []
        days_to_work = randint(1,5)
        for day in range(days_to_work):
            if not day in work_days:
                work_days.append(day)
                start_time = datetime.strptime(f'0{randint(7, 9)}:00', '%H:%M')
                end_time = datetime.strptime(f'{randint(10, 18)}:00', '%H:%M')
                EmployeeWorkingHours.objects.create(week_day=day, start_time=start_time, end_time=end_time, employee=emp)

warehouses/views.py
# warehouses.views.py
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.http.response import HttpResponse as HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, FormView
from .models import Item, EmployeeWorkingHours, ItemEdit, Employee, ItemOrder
from .forms import ItemForm, OrderItemsForm
from django.db.models import Q, Count, Min, F
from django.db import transaction
from django.template.response import TemplateResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from user.custom_mixins import StaffRequiredMixin

# Create your views here.

def menu_links_style(exclude):
    links = [
        {"link":("index", ()), "name":"Home", "menu":[{"link":("index", ()), "name":"Home"}, {"link":("about", ()), "name":"About"}, {"link":("products", "ALL"), "name":"All Products"}, {"link":("search", "ALL"), "name":"Search all products"}, {"link":("filtered", ["ALL", "category"]), "name":"Search products by category"}, {"link":("filtered", ["ALL", "state"]), "name":"Search products by state"}]},
        {"link":("warehouse", "EU"), "name":"Awarehouse", "menu":[{"link":("warehouse", "EU"), "name":"Awarehouse Home"}, {"link":("products", "EU"), "name":"EU Products"}, {"link":("search", "EU"), "name":"Search EU products"}, {"link":("filtered", ["EU", "category"]), "name":"Search EU products by category"}, {"link":("filtered", ["EU", "state"]), "name":"Search EU products by state"}]},
        {"link":("warehouse", "USA"), "name":"Bewarehouse", "menu":[{"link":("warehouse", "USA"), "name":"Bewarehouse Home"}, {"link":("products", "USA"), "name":"USA Products"}, {"link":("search", "USA"), "name":"Search USA products"}, {"link":("filtered", ["USA", "category"]), "name":"Search USA products by category"}, {"link":("filtered", ["USA", "state"]), "name":"Search USA products by state"}]},
        {"link":("warehouse", "ASIA"), "name":"Seawarehouse", "menu":[{"link":("warehouse", "ASIA"), "name":"Seawarehouse Home"}, {"link":("products", "ASIA"), "name":"ASIA Products"}, {"link":("search", "ASIA"), "name":"Search ASIA products"}, {"link":("filtered", ["ASIA", "category"]), "name":"Search ASIA products by category"}, {"link":("filtered", ["ASIA", "state"]), "name":"Search ASIA products by state"}]},
        {"link":("warehouse", "INDIA"), "name":"Dewarehouse", "menu":[{"link":("warehouse", "INDIA"), "name":"Dewarehouse Home"}, {"link":("products", "INDIA"), "name":"INDIA Products"}, {"link":("search", "INDIA"), "name":"Search INDIA products"}, {"link":("filtered", ["INDIA", "category"]), "name":"Search INDIA products by category"}, {"link":("filtered", ["INDIA", "state"]), "name":"Search INDIA products by state"}]},
    ]
    def un_menu(link:dict):
        if "menu" in link.keys():
            link["menu"] = [l for l in link["menu"] if not l["link"] == exclude]
        elif link["link"] == exclude:
            menu = link["menu"][1:]
            link = link["menu"][0]
            link["menu"] = menu
        return link
    links = [un_menu(link) for link in links]
    if type(exclude[1]) == list:
        exclude = exclude[1]
    stc = "a" if "EU" in exclude else \
        "b" if "USA" in exclude else \
        "c" if "ASIA"  in exclude else \
        "d" if "INDIA"  in exclude else "e"
    style = f'warehouses/css/style_{stc}ware.css'

    continent = "Europe" if stc == "a" else \
        "the United States of America" if stc == "b" else \
            "Asia" if stc == "c" else "India" if stc == "d" \
            else "all our warehouses"

    return links, style, continent


class RegisterView(TemplateView):
    '''View containing registration etc'''
    template_name = "registration/reg_container.html"
    
def get_reg_from_request(request):
    view = RegisterView.as_view()
    # Render the view and get the response content
    response = view(request)
    if isinstance(response, TemplateResponse):
        return response.render().content
    else:
        # Handle non-TemplateResponse cases
        return response.content

class NotFound(TemplateView):
    template_name = "not_found.html"

class Index(TemplateView):
    template_name = "main.html"
    links, style, continent = menu_links_style(("index", ()))
    
    def get_context_data(self):
        context = {
            "reg": get_reg_from_request(self.request),
            "links": self.links,
            "title": "shopping 2.0",
            "header_text": "Welcome to shopping 2.0",
            "content_text": ["The future of social marketing."]
        }
        return context


class About(TemplateView):
    template_name = "about.html"
    links, style, continent = menu_links_style(("about", ()))
    def get_context_data(self):
        return {
            "reg": get_reg_from_request(self.request),
            "links": self.links,
            "title":"about shopping 2.0",
            "header_text":"about us",
            "content_text":["We believe in humanity to be able to stop the waste of all goods we're provided.", 
                    "We refurbish products and provide them to prices you can set yourself.",
                    "We expect everybody to be able to value what he deserves.",
                    "We want everybody to be able to get what's needed.",
                    " "
                    "You can consider your payment as appreciation of the product and our imparting.",
                    "If you can afford feel free to consider the price you pay as a donation for others who own less.",
                    "If you don't have much and want to get a lot please give a reasonable comment on why.",
                    "Avarice will never hurt us, but probably you."]
        }

class Warehouse(TemplateView):
    template_name = "warehouse.html"
    def get_context_data(self, location):
        super().get_context_data()
        links, style, continent = menu_links_style(("warehouse", location))
        return {
            "reg": get_reg_from_request(self.request),
            "style":style,
            "links": links,
            "location":location,
            "title":f"{'A' if location == 'EU' else 'B' if location == 'USA' else 'C' if location == 'ASIA' else 'D'}-Warehouse {location}",
            "header_text":f"Shopping 2.0 in {continent}",
            "content_text":[f"Explore our shop in {continent}.",
                "Our offers are collected from donations, private people, misproductions and so on.",
                "You define what to pay.",
                "Please place reasonable prices and comment on why in case you cannot."]
        }

class Products(TemplateView):
    template_name = "warehouse.html"
    def get_context_data(self, location):
        links, style, continent = menu_links_style(("products", location))
        first_pk = F('id')
        if location == "ALL":
            content = Item.objects.filter(shipped=False).values("category", "state").annotate(count=Count('id'), pk=Min(first_pk)).distinct()
        else:
            wh = 1 if location == "EU" else 2 if location == "USA" else 3 if location == "ASIA" else 4
            content = Item.objects.filter(warehouse=wh, shipped=False).values("category", "state").annotate(count=Count('id'), pk=Min(first_pk)).distinct()
        return {
            "reg": get_reg_from_request(self.request),
            "style":style,
            "links": links,
            "location":location,
            "title":f"{'A' if location == 'EU' else 'B' if location == 'USA' else 'C' if location == 'ASIA' else 'D' if location == 'INDIA' else 'Your'}-Warehouse {location if location != 'ALL' else ''}",
            "header_text":f"Products in {continent}",
            "content_text":[f"Here is a list of all Products in {continent} ({len(content)} in total):"],
            "content":content
        }



class ProductDetailView(StaffRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = "product_detail.html"
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('thanks', args=["update"])

    def form_valid(self, form):
        self.object = form.save()
        emp = Employee.objects.filter(user_id=self.request.user.pk).first()
        ItemEdit.objects.create(employee=emp, item=self.object)
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        content = self.get_object()
        wh = content.warehouse_id
        location = "EU" if wh == 1 else "USA" if wh == 2 else "ASIA" if wh == 3 else "INDIA" # if wh == 4 else "ALL"
        links, style, continent = menu_links_style(("product", location))
        context.update({
            "reg": get_reg_from_request(self.request),
            "style":style,
            "links": links,
            "location":location,
            "title":f"{'A' if location == 'EU' else 'B' if location == 'USA' else 'C' if location == 'ASIA' else 'D' if location == 'INDIA' else 'Your'}-Warehouse {location if location != 'ALL' else ''}",
            "header_text":f"Update Item #{content.pk} from {location}"
        })
        return context
    

class OrderView(LoginRequiredMixin, StaffRequiredMixin, FormView):
    template_name = 'product_order.html'
    form_class = OrderItemsForm
    success_url = reverse_lazy('thanks', args=["order"])

    @transaction.atomic
    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        items_to_order = Item.objects.filter(
            state=self.state, category=self.category, shipped=False
        )
        items_to_order = items_to_order.order_by('id')[:amount]
        emp = Employee.objects.filter(user_id=self.request.user.pk).first()
        item_order = ItemOrder.objects.create(employee=emp, amount=amount)
        for item in items_to_order:
            item_order.item.add(item)

warehouses/templates/about.html
{% extends "main.html" %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'warehouses/css/style_about.css' %}">
{% endblock %}

warehouses/templates/employees.html
{% extends "main.html" %}
{% load custom_filters %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static style %}">
    <style>
        .italic-link {
          font-style: italic;
        }
    </style>
{% endblock %}
{% block content%}
<ul>
    {% for employee, working_hours in employee_working_hours.items %}
        <li>{{ employee.name }}</li>
        <ul>
            {% for hour in working_hours %}
                <li>{{ hour.get_week_day_display }}: {{ hour.start_time }} - {{ hour.end_time }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>


{% endblock %}

warehouses/templates/main.html
<!DOCTYPE html>
{% load static %}
{% load custom_filters %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'warehouses/css/style.css' %}">
    {% block extra_css %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <div class="loginShower" id="loginShower">
        <h4>Refurbish is responsibility.</h4>
        <h5>Account</h5>
        <div class="login" id="loginForm">
            {% include 'registration/reg_container.html' %}
        </div>
    </div>
    <header style="min-height: 120px;">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid" id="vanishingInv">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">          
                    {% for link in links %}
                        <li class="nav-item">
                            {% if not link.link.1 %}
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">{{ link.name }}</a>
                                <ul class="dropdown-menu" style="background-color: rgba(0, 0, 0, 0.233);">
                                {% for menu_link in link.menu %}
                                    <div class="dropContent link">
                                        {% with path=menu_link.link.1%}
                                                {% if not path %}
                                                    <li><a class="dropdown-item" href="{% url menu_link.link.0 %}">{{menu_link.name}}</a></li>
                                                {% elif not path|is_list %}
                                                    <li><a class="dropdown-item" href="{% url menu_link.link.0 path %}">{{menu_link.name}}</a></li>
                                                {% else %}
                                                    <li><a class="dropdown-item" href="{% url menu_link.link.0 path.0 path.1 %}">{{menu_link.name}}</a></li>
                                                {% endif %}
                                        {% endwith %}
                                    </div>
                                {% endfor %}
                                </ul>
                            {% else %}
                                {% with path=link.link.1%}
                                    <a class="nav-link dropdown-toggle" href="{% url link.link.0 path %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ link.name }}</a>
                                    <ul class="dropdown-menu" style="background-color: rgba(0, 0, 0, 0.233);">
                                    {% for menu_link in link.menu %}
                                        <div class="dropContent link">
                                            {% with paths=menu_link.link.1%}
                                                    {% if not paths|is_list %}
                                                        <li><a class="dropdown-item" href="{% url menu_link.link.0 paths %}">{{menu_link.name}}</a></li>
                                                    {% else %}
                                                        <li><a class="dropdown-item" href="{% url menu_link.link.0 paths.0 paths.1 %}">{{menu_link.name}}</a></li>
                                                    {% endif %}
                                            {% endwith %}
                                        </div>
                                    {% endfor %}
                                {% endwith %}
                                </ul>
                            {% endif %}
                        </li> 
                    {% endfor %}
                </ul>
            </div>    
        </div>
    </nav>
    </header>
    <main>
        <section>
            <div style="width: 35%;" class="mainSec">
                <h1>{{header_text}}</h1>
                {% for content in content_text %}
                    <h5 style="font-weight: 50;">{{content}}</h5>
                {% endfor %}
            </div>
            <div style="max-height: 70vh; overflow-y: auto; padding-right: 20px;">
                {% block content %}{% endblock %}
            </div>
        </section>
    </main>
    <footer>
        <p><a href="#link" class="link">Impressum</a></p>
        <p><a href="#link" class="link">Copyright</a></p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'warehouses/scripts/script.js' %}"></script>
</body>
</html>

warehouses/templates/not_found.html
{% extends "main.html" %}
{% load static %}
{% block content %}
<h1>We don't know what you're looking for...</h1>
{% endblock %}

warehouses/templates/product_detail.html
{% extends "main.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static style %}">
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{form|crispy }}
    <input class="btn btn-outline-light" type="submit" name="submit" value="Update">
</form>
{% endblock %}

warehouses/templates/product_order.html
{% extends "main.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static style %}">
{% endblock %}
{% block content %}
<h3>Select the number of {{ product }} items you want to purchase:</h3>
<form method="post">
    {% csrf_token %}
    {{form|crispy }}
    <input class="btn btn-outline-light" type="submit" name="submit" value="Order now.">
</form>
{% endblock %}

warehouses/templates/thanks.html
{% extends "main.html" %}
{% load static %}
{% block content %}
<h1>Thanks!</h1>
<p>{{ message }}</p>
{% endblock %}

warehouses/templates/warehouse.html
{% extends "main.html" %}
{% load custom_filters %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static style %}">
{% endblock %}
{% block content%}
    {% for item in content%}
        <div style="display: flex; justify-content: end;">
        {% if item.category|ends_with_s %}
        <p><a href="{% url 'filtered_items' location 'state' item.state %}">{{item.state}}</a> <a href="{% url 'filtered_items' location 'category' item.category %}">{{item.category}}</a>. {% if item.count %} ({{item.count}} available) {% endif %}{% if user.is_authenticated and user.is_staff%} <a class="btn btn-outline-warning" href="{% url 'product_detail' item.pk %}" class="italic-link" style="margin-left: 20px;">(update here)</a><a class="btn btn-outline-danger" href="{% url 'order' location item.state item.category %}" class="bold-link" style="margin-left: 20px;"> BUY</a>{% endif %}</p>
        {% else %}
        <p><a href="{% url 'filtered_items' location 'state' item.state %}">{{item.state|glue}}</a> <a href="{% url 'filtered_items' location 'category' item.category %}">{{item.category}}</a>. {% if item.count %} ({{item.count}} available) {% endif %}{% if user.is_authenticated and user.is_staff%} <a class="btn btn-outline-warning" href="{% url 'product_detail' item.pk %}" class="italic-link" style="margin-left: 20px;">(update here)</a><a class="btn btn-outline-danger" href="{% url 'order' location item.state item.category %}" class="bold-link" style="margin-left: 20px;"> BUY</a>{% endif %}</p>
        {% endif %}
        </div>
    {% endfor %}
    {% for link in content_links %}
    <div style="display: flex; justify-content: end;">
        {% if filtered_by == 'category' %}
        <p><a href="{% url 'filtered_items' location 'category' link.category %}">{{link.category}}</a>.{% if link.count %} ({{link.count}} available) {% endif %}</p>
        {% elif filtered_by == 'name' %}
        <p><a href="{% url 'filtered_items' location 'state' link.state %}">{{link.state|glue}}</a> <a href="{% url 'filtered_items' location 'category' link.category %}">{{link.category}}</a>.{% if link.count %} ({{link.count}} available) {% endif %}{% if user.is_authenticated and user.is_staff %}<a class="btn btn-outline-danger" href="{% url 'order' location link.state link.category %}" class="bold-link" style="margin-left: 20px;"> BUY</a>{% endif %}</p>
        {% else %}
        <p><a href="{% url 'filtered_items' location 'state' link.state %}">{{link.state}}</a>.{% if link.count %} ({{link.count}} available) {% endif %}</p>
        {% endif %}
    </div>
    {% endfor %}
    {% if search_item %}
        <h3>{{search_prompt}}</h3>
            <div style="display: flex;">
                <input  class="form-control" id="searchInput" type="text" placeholder="enter search term here" onkeydown="start_search(this)">
                <button class="btn btn-outline-light" onclick="search()" style="margin-left: 20px;">Search</button>
            </div>
        <script>
            function start_search(element) {
                if(event.key === 'Enter') {
                    search()
                }
            }
            function search() {
                // Get the value from the search input
                var searchTerm = document.getElementById("searchInput").value;

                // Construct the URL with the search term
                var url = "{% url 'search_result' location|default:'ALL' 'SEARCHTERM' %}".replace("SEARCHTERM", encodeURIComponent(searchTerm));


                // Redirect the user to the search URL
                window.location.href = url;
            }
        </script>
    {% endif %}
{% endblock %}